### ISSUE TITLE
[BUG] Restoring iPod Touch 2 to 2.1.1 - error in py file

### ISSUE THREAD

**Issue by nmka55** [LukeZGD/Legacy-iOS-Kit#448]
```

 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.03.36 (ad57fab)
* Platform: macos (14.4.1) 

* Device: iPod2,1 (n72ap) in Recovery mode
* iOS Version: ::	BUILD_TAG: iBoot-385.22
* ECID: 3873289375158

 > Main Menu > Restore/Downgrade
* Select "Other (Custom IPSW)" to restore to any other iOS version (2.1.1 to 3.0)

* New bootrom devices might be incompatible with older iOS versions

[Input] Select an option:
1) 4.1			4) Latest iOS (4.2.1)	7) IPSW Downloader
2) 3.1.3		5) Other (Custom IPSW)	8) Go Back
3) More versions	6) DFU IPSW
#? 5
* You are about to restore with a custom IPSW.
* This option is only for restoring with IPSWs NOT made with Legacy iOS Kit, like whited00r or GeekGrade.
* You may also use this option for downgrading the device to 3.0 and lower for old bootrom models.
[Input] Press Enter/Return to continue (or press Ctrl+C to cancel)
[Input] Select your target IPSW file in the file selection window.
[Log] Selected IPSW file: /Users/nyambayaramarsaikhan/Downloads/Legacy-iOS-Kit_macos_v24.03.18/iPod2,1_2.1.1_5F138_Restore.ipsw
[Log] Getting version from IPSW
Archive:  /Users/nyambayaramarsaikhan/Downloads/Legacy-iOS-Kit_macos_v24.03.18/iPod2,1_2.1.1_5F138_Restore.ipsw
  inflating: ./Restore.plist         
* Get ready to enter DFU mode.
* If you already know how to enter DFU mode, you may do so right now before continuing.
[Input] Select Y to continue, N to exit recovery mode (Y/n) y
* Get ready...
2 1 
* Hold TOP and HOME buttons.
10 9 8 7 6 5 4 3 2 1 
* Release TOP button and keep holding HOME button.
8 7 6 5 4 3 2 1 
[Log] Finding device in DFU mode...
[Log] Found device in DFU mode.
[Log] python2 from pyenv detected
[Log] Placing device to pwnDFU Mode using ipwndfu
Traceback (most recent call last):
  File "ipwndfu", line 49, in <module>
    device = dfu.acquire_device()
  File "/Users/nyambayaramarsaikhan/Downloads/Legacy-iOS-Kit_macos_v24.03.18/saved/ipwndfu/dfu.py", line 16, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Users/nyambayaramarsaikhan/Downloads/Legacy-iOS-Kit_macos_v24.03.18/saved/ipwndfu/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
[Error] Failed to enter pwnDFU mode. Please run the script again.

* Exit DFU mode first by holding the TOP and HOME buttons for about 10 seconds.
* If you get the error "No backend available" in ipwndfu, install libusb in Homebrew/MacPorts: brew install libusb
* For more details, read the "Troubleshooting" wiki page in GitHub
* Troubleshooting links:
    - https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting
    - https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Pwning-Using-Another-iOS-Device
* Legacy iOS Kit v24.03.36 (ad57fab)
* Platform: macos (14.4.1) 
nyambayaramarsaikhan@Nyambayars-MacBook-Pro Legacy-iOS-Kit_macos_v24.03.18 % 

```

**Comment by LukeZGD** [comment]
install libusb in Homebrew/MacPorts
