### ISSUE TITLE
usb.core.USBError: [Errno 32] Pipe error

### ISSUE THREAD

**Issue by AZGDO** [LukeZGD/Legacy-iOS-Kit#504]
I want to flash a CFW to my iPad 3, i pwned it via arduino but when i try to send pwned ibss it says: ```
Traceback (most recent call last):
  File "ipwndfu", line 85, in <module>
    device = usbexec.PwnedUSBDevice()
  File "/Users/azgd0/Legacy-iOS-Kit/saved/ipwndfu/usbexec.py", line 150, in __init__
    info = self.read_memory(self.image_base() + 0x200, 0x100)
  File "/Users/azgd0/Legacy-iOS-Kit/saved/ipwndfu/usbexec.py", line 92, in read_memory
    response = self.command(self.cmd_memcpy(self.cmd_data_address(0), address + len(data), part_length), self.cmd_data_offset(0) + part_length)
  File "/Users/azgd0/Legacy-iOS-Kit/saved/ipwndfu/usbexec.py", line 111, in command
    response = device.ctrl_transfer(0xA1, 2, 0xFFFF, 0, response_length, CMD_TIMEOUT).tostring()
  File "/Users/azgd0/Legacy-iOS-Kit/saved/ipwndfu/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/Users/azgd0/Legacy-iOS-Kit/saved/ipwndfu/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/Users/azgd0/Legacy-iOS-Kit/saved/ipwndfu/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 32] Pipe error
```
I'm using Macbook Pro on M3 Pro, already tried iPad 3, and two iPad's 2, all same, using synackuk's checkm8-a5 to enter pwned dfu.

**Comment by LukeZGD** [comment]
synackuk's fork is known to have issues with iPad 3, try my fork of checkm8-a5: https://github.com/LukeZGD/checkm8-a5

**Comment by AZGDO** [comment]
THANKS THAT WORKED!!!
