### ISSUE TITLE
Entering pwnDFU fails for iPod Touch 2nd generation

### ISSUE THREAD

**Issue by zillionbear** [LukeZGD/Legacy-iOS-Kit#639]
Attempting to downgrade iPod Touch 2G to iOS 3.1.3 fails because pwnDFU mode can't be entered. I've installed python 2.7.18. Also installed libusb (through MacPorts). Running macOS 15.1.1 on M1. iPod has new bootrom.

Saved terminal output:

```
 *** Legacy iOS Kit ***
 - Script by LukeZGD -

* Version: v24.12.18 (7178ee4)
* Platform: macos (15.1.1 - arm64) 

* Device: iPod touch 2 (iPod2,1 - n72ap) in DFU mode
* This iPod touch 2 is a new bootrom model
* iOS Version: Unknown
* To get iOS version, go to: Other Utilities -> Get iOS Version
* ECID: 72645533135

* Only select unmodified IPSW for the selection. Do not select custom IPSWs

* Selected Target IPSW: ../iPod2,1_3.1.3_7E18_Restore.ipsw
* Selected Target IPSW is validated

 > Main Menu > Restore/Downgrade > 3.1.3
[Input] Select an option:
1) Select Target IPSW	 3) Start Restore
2) Download Target IPSW	 4) Go Back
#? 3
[Log] Jailbreak option is not available for this version. You may jailbreak later after the restore
* To jailbreak, select "Jailbreak Device" in the main menu
[Input] Memory Option for creating custom IPSW
* When this option is enabled, system RAM will be used for the IPSW creation process.
* I recommend to enable this option to speed up creating the custom IPSW.
* However, if your PC/Mac has less than 8 GB of RAM, disable this option.
* This option is enabled by default (Y). Select this option if unsure.
[Input] Enable this option? (Y/n): 
[Log] Memory option enabled.

[Log] Found existing Custom IPSW. Skipping IPSW creation.
[Log] Placing device to pwnDFU Mode using ipwndfu
Acquiring device handle.
Traceback (most recent call last):
  File "ipwndfu", line 49, in <module>
    device = dfu.acquire_device()
  File "/Applications/Legacy iOS Kit/saved/ipwndfu/dfu.py", line 16, in acquire_device
    for device in usb.core.find(find_all=True, idVendor=0x5AC, idProduct=0x1227, backend=backend):
  File "/Applications/Legacy iOS Kit/saved/ipwndfu/usb/core.py", line 1263, in find
    raise NoBackendError('No backend available')
usb.core.NoBackendError: No backend available
[Error] Failed to enter pwnDFU mode. Please run the script again.

* Exit DFU mode first by holding the TOP and HOME buttons for about 10 seconds.
* If you get the error "No backend available" in ipwndfu, install libusb in Homebrew/MacPorts
* For more details, read the "Troubleshooting" wiki page in GitHub
* Troubleshooting links:
    - https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Troubleshooting
    - https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Pwning-Using-Another-iOS-Device

* Save the terminal output now if needed. (macOS: Cmd+S, Linux: Ctrl+Shift+S)
* Legacy iOS Kit v24.12.18 (7178ee4)
* Platform: macos (15.1.1 - arm64) 
user@Users-MacBook-Pro Legacy iOS Kit % 
```

**Comment by LukeZGD** [comment]
check the output of this command: `ls -la ~/lib/libusb-1.0.dylib`

**Comment by zillionbear** [comment]
Output:

`lrwxr-xr-x  1 root  admin  18 Dec 25 17:30 /Users/user/lib/libusb-1.0.dylib -> libusb-1.0.0.dylib`

**Comment by LukeZGD** [comment]
hmm, looks fine.. not sure why you're having that issue since im having no issue on my m2 (i do have macports and homebrew)

**Comment by LukeZGD** [comment]
i have pushed an update that changes macos libusb handling a bit.

let me know if you see something like this: https://i.imgur.com/NeavNfw.jpeg

or this: https://i.imgur.com/x3eNb0v.jpeg

(where i deliberately uninstalled libusb to test)

make sure that you are using v25.01.05
